# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

configs = YAML.load_file("../../pillar/site_petc.sls")
psrv = configs['sample']['petclinic']['physical_server']

Vagrant.configure("2") do |config|
  psrv.each do |key,val|

    script = <<SCRIPT
      cat /vagrant/id_rsa.pub >> /home/"#{val['user']}"/.ssh/authorized_keys
SCRIPT

    config.vm.define val['hostname'] do |cfg|
      cfg.vm.box = "ubuntu/xenial64"
      cfg.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
      cfg.vm.network "private_network", ip: "#{val['ip']}"
      cfg.vm.host_name = val['hostname']
      #cfg.vm.synced_folder ".", "/vagrant", disabled: true
      cfg.vm.provision :shell, :inline => script
    end
  end
end
