# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    script = <<SCRIPT
      sudo useradd -m "sungsic"
      sudo mkdir /home/sungsic/.ssh
      sudo chown sungsic:sungsic /home/sungsic/.ssh
      cat /vagrant/id_rsa.pub >> /home/sungsic/.ssh/authorized_keys
      sudo echo "sungsic    ALL=NOPASSWD: ALL" >> /etc/sudoers
SCRIPT
    config.vm.define "test1" do |cfg|
      cfg.vm.box = "ubuntu/xenial64"
      cfg.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
      cfg.vm.network "private_network", ip: "172.28.128.100"
      cfg.vm.host_name = "test1"
      #cfg.vm.synced_folder ".", "/vagrant", disabled: true
      cfg.vm.provision :shell, :inline => script
    end
    config.vm.define "test2" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
      cfg.vm.network "private_network", ip: "172.28.128.101"
      cfg.vm.host_name = "test2"
      #cfg.vm.synced_folder ".", "/vagrant", disabled: true
      cfg.vm.provision :shell, :inline => script
    end

end
