# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

#configs = YAML.load_file("../../pillar/site_ozr.sls")
#psrv = configs['hwbc']['ozr']['physical_server']
psrv = { 
'master' => { 'hostname' => 'hdmaster', 'ip' => '172.28.128.100', 'user' => 'ubuntu'},
'slave1' => { 'hostname' => 'hdslave1', 'ip' => '172.28.128.101', 'user' => 'ubuntu'},
'slave2' => { 'hostname' => 'hdslave2', 'ip' => '172.28.128.102', 'user' => 'ubuntu'},
'slave3' => { 'hostname' => 'hdslave3', 'ip' => '172.28.128.103', 'user' => 'ubuntu'},
}

Vagrant.configure("2") do |config|
  psrv.each do |key,val|

    script = <<SCRIPT
      sudo apt-get update
      cat /vagrant/id_rsa.pub >> /home/"#{val['user']}"/.ssh/authorized_keys
SCRIPT

    config.vm.define val['hostname'] do |cfg|
      cfg.vm.box = "ubuntu/xenial64"
      cfg.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
      cfg.vm.network "private_network", ip: "#{val['ip']}"
      cfg.vm.host_name = val['hostname']
#     cfg.vm.synced_folder ".", "/vagrant", disabled: true
#      cfg.vm.provision :shell, :inline => script
    end
  end
end
